#!/bin/sh
# XXX: Run this from a monitor node
# usage: ./cephdump

# directory name format: MMDDYY_HHMMSS
dir="/tmp/$(date +%D_%T| tr -d '/:')"

# default ceph log directory
logdir=/var/log/ceph

# get version details from ceph and the respective binaries
getversion() {
	savedir=$dir/version
	mkdir -p $savedir

	for bin in /usr/bin/ceph*
	do
		nohup $bin -v > $savedir/version_"$(basename $bin)".txt
	done
	
	for service in mgr mds mon osd
	do
		nohup ceph $service versions > $savedir/version_$service.txt
	done
}

# get the ceph.conf
getconf() {
	mkdir -p $dir/conf
	[ -d /etc/ceph ] && cp -rv /etc/ceph $dir/conf
}

# get a copy of ceph's log directory
getlogs() {
	[ -d $logdir ] && mkdir -p $dir/logs
	cp -rv $logdir $dir/logs
}

# get osd and CRUSH details along with the binary of the osd and crush map
getosd() {
	savedir=$dir/osd
	mkdir -p $savedir
	nohup ceph osd metadata > $savedir/osd_metadata.txt
	nohup ceph osd df tree > $savedir/df-tree.txt
	nohup ceph osd crush tree > $savedir/crush-tree.txt
	nohup ceph osd stat > $savedir/osd-stat.txt
	ceph osd getmap -o $savedir/osdmap.bin
	ceph osd getcrushmap -o $savedir/crushmap.bin
	nohup ceph osd dump > $savedir/osd_dump.txt
	nohup ceph osd crush dump > $savedir/crush_dump.txt
	nohup ceph osd crush rule dump > $savedir/crush_rule.txt
}

# get mds details
getmds() {
	savedir=$dir/mds
	mkdir -p $savedir
	nohup ceph mds stat > $savedir/mds_stat.txt
	nohup ceph mds metadata > $savedir/mds_metadata.txt
}

# get the monitor details along with the binary of the monitor map
getmon() {
	savedir=$dir/mon
	mkdir -p $savedir
	nohup ceph mon metadata > $savedir/mon_metadata.txt
	nohup ceph auth ls > $savedir/auth.txt
	ceph mon getmap -o $savedir/monmap.bin
	nohup ceph quorum_status -f json-pretty > $savedir/mon_quorum_status.txt
	nohup ceph mon stat > $savedir/mon_stat.txt
	nohup ceph mon dump > $savedir/mon_dump.txt
}

# get manager details and the modules in use
getmgr() {
	savedir=$dir/mgr
	mkdir -p $savedir
	nohup ceph mgr metadata > $savedir/mgr_metadata.txt
	nohup ceph mgr dump > $savedir/mgr_dump.txt
	nohup ceph mgr module ls > $savedir/mgr_mods.txt
}

# get cluster health, size and pg details
gethealth() {
	nohup ceph -s > status.txt
	nohup ceph health detail > health.txt
	nohup ceph df detail > df.txt
	nohup rados df > rados-df.txt
	nohup ceph pg ls > pg.txt
}

# get all the pool and their respective image details
getpool() {
	savedir=$dir/pool
	mkdir -p $savedir

	nohup ceph osd pool ls detail > $savedir/pool_details.txt
	for pool in $(rados lspools)
	do
		nohup rbd -p $pool ls > $savedir/pool_"$pool"_images.txt
		nohup rbd -p $pool ls | while read img; do nohup rbd info -p $pool $img > $savedir/pool_"$pool"_"$img"_details.txt; done
	done
}

# create a tarball archive of the dump directory
archive() {
	out="$dir".tar.xz
	cd /tmp
	echo "archiving as $out"
	tar -cJvf $out $dir 1> /dev/null && echo "Saved as: $out"
}

cleanup() {
	echo "Removing $dir directory"
	rm -fr $dir
}

main() {
	[ ! -d $dir ] && mkdir -p $dir && cd $dir

	getversion
	gethealth
	getlogs
	getconf
	getosd
	getmon
	getmds
	getmgr
	getpool
	archive && cleanup
}
main
